name: Clean Data Files  
  
on:  
  workflow_dispatch:  
    inputs:  
      confirm_clean:  
        description: 'Type "CONFIRM" to proceed with cleaning'  
        required: true  
        default: ''  
  
jobs:  
  clean:  
    runs-on: ubuntu-latest  
    if: github.event.inputs.confirm_clean == 'CONFIRM'  
      
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  
        with:  
          fetch-depth: 0  
          persist-credentials: true  
  
      - name: Clean data files  
        run: |  
          rm -f run_page/data.db  
          rm -rf GPX_OUT/* TCX_OUT/* FIT_OUT/* activities/* || true  
          rm -f src/static/activities.json  
          echo "Data files cleaned successfully"  
  
      - name: Commit changes  
        run: |  
          git config --local user.email "action@github.com"  
          git config --local user.name "GitHub Action"  
          git add .  
          git commit -m "Clean data files via GitHub Actions" || echo "No changes to commit"  
          git push || echo "Nothing to push"
